---
version: '1'

# App (Project) name
name: FX-Example-2

# App description
description: Testing the FX SaaS Platform

# license
licenses:
  - APACHE LICENSE, VERSION 2.

imports:
  '@USName': FXLabs/Common/US-Names

# App environments
environments:
  - name: Dev
    baseUrl: http://13.57.51.56/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.local
        password: '{{@Vault.FXLabs/password}}'

# Job profiles
jobs:
  - name: Dev
    environment: Dev
    tags:
      - V1
    regions: FXLabs/Localhost
    cron: '0 0 12 * * ?'
    issueTracker: 
      name: FX-Example-IssueTracker
      url: https://github.com/intesar/FX-Example
      account: Default_GitHub
    notifications: 
      - name: FX-Example-Slack-Notification
        channel: engineering
        account: Default_Slack
      - name: FX-Example-Email-Notification
        # enter your email
        to: intesar@fxlabs.io
        account: Default_Email
